#
# Basic workflow to update website:
#  1. make changes and use $hugo server -D (possible adding '-p PORT' if needed) 
#  2. $ hugo (to build the /public folder containing the static website)
#  3. $ cd public 
#  4. $ git add . 
#  5. $ git commit -m "my changes"
#  6. $ git push origin master (public is a submodule pointing to fabgilson.github.io magic repo) 
#  7. $ rm -rf public
#  8. $ git add the changes and push them
#
# One day, make a script :) 
#

baseURL = "https://fabgilson.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Fabian Gilson's website"
theme = "hugo-anatole-fork"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Hi there, I'm Fabian"
author = "Fabian Gilson"
description = "Some stuff about me and my work"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
customCss = ["css/style.css"]
customJs = ["js/all.js"]
mainSections = ["post"]
readMore = true
# images = ["images/site-feature-image.png"]

## Font
google_fonts = [
  ["Josefin Sans", "400, 700"],
  ["Istok Web", "400, 400i, 700, 700i"]
]

## Math settings
#[params.math]
#enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
#use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/FabGilson/"

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/fabiangilson/"

[[params.socialIcons]]
icon = "fab fa-gitlab"
title = "gitlab"
url = "https://gitlab.com/mde4asd/"

[[params.socialIcons]]
icon = "fab fa-researchgate"
title = "ResearchGate"
url = "https://www.researchgate.net/profile/Fabian_Gilson"

[[params.socialIcons]]
icon = "fab fa-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0002-1465-3315"


[[params.socialIcons]]
icon = "fa-id-card"
title = "University of Canterbury's webpage"
url = "https://www.canterbury.ac.nz/engineering/contact-us/people/fabian-gilson.html"

## Menu items

[menu]

  [[menu.main]]
  name = "home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "research"
  weight = 200
  identifier = "research"
  url = "/research/"

  [[menu.main]]
  name = "courses"
  weight = 300
  identifier = "courses"
  url = "/courses/"

  [[menu.main]]
  name = "posts"
  weight = 400
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "about"
  weight = 500
  identifier = "about"
  url = "/about/"